# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unic_candidat', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('sex', models.CharField(blank=True, max_length=1024, null=True)),
                ('specializare', models.CharField(blank=True, max_length=1024, null=True)),
                ('profil', models.CharField(blank=True, max_length=1024, null=True)),
                ('fileira', models.CharField(blank=True, max_length=1024, null=True)),
                ('forma_de_invatamant', models.CharField(blank=True, max_length=1024, null=True)),
                ('mediu_candidat', models.CharField(blank=True, max_length=1024, null=True)),
                ('unitate_siiir', models.CharField(blank=True, max_length=1024, null=True)),
                ('unitate_sirues', models.CharField(blank=True, max_length=1024, null=True)),
                ('clasa', models.CharField(blank=True, max_length=1024, null=True)),
                ('subiect_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('subiect_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('limba_moderna', models.CharField(blank=True, max_length=1024, null=True)),
                ('subiect_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('subiect_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('promotie', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_a', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_b', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_c', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_d', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('note_recun_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_a', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_b', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_c', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_d', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('ita', models.CharField(blank=True, max_length=1024, null=True)),
                ('scris_itc', models.CharField(blank=True, max_length=1024, null=True)),
                ('scris_pms', models.CharField(blank=True, max_length=1024, null=True)),
                ('oral_pmo', models.CharField(blank=True, max_length=1024, null=True)),
                ('oral_io', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('contestatie_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_contestatie_ea', models.CharField(blank=True, max_length=1024, null=True)),
                ('contestatie_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_contestatie_eb', models.CharField(blank=True, max_length=1024, null=True)),
                ('contestatie_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_contestatie_ec', models.CharField(blank=True, max_length=1024, null=True)),
                ('contestatie_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('nota_contestatie_ed', models.CharField(blank=True, max_length=1024, null=True)),
                ('punctaj_digitale', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('medie', models.CharField(blank=True, max_length=1024, null=True)),
                ('anul', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
